# Generated by Django 5.0.4 on 2024-04-11 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contas.instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='instituicao',
            name='tipo_instituicao',
            field=models.ManyToManyField(to='contas.tipoinstituicao'),
        ),
    ]
