# Generated by Django 5.0.4 on 2024-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(default='', max_length=128),
        ),
    ]
